export const ACCEPTABLE = new Set([
  'Parked on free space',
  'Neatly aligned against surroundings',
  'Parked at bike rack',
  'Parked in dedicated parking zone',
  'Parked in a car parking space',
  'Niche Parking',
  'Cobble Stone Strip inner side',
  'Cobble Stone Strip outer side',
])

export const LABEL_DE = {
  'Invalid':                             'Kein gültiges Rollerfoto',
  'Parked on grass or in a tree pit':    'Auf Grünfläche oder Baumscheibe',
  'Blocking an entrance':                'Einfahrt blockiert',
  'Parked on the sidewalk':              'Auf dem Gehweg',
  'Parked on a bike lane':               'Auf dem Radweg',
  'Knocked over':                        'Umgekippt',
  'Badly aligned with surroundings':     'Schlecht ausgerichtet',
  'Blocking a crosswalk':                'Fußgängerüberweg blockiert',
  'Parked too near to a corner':         'Zu nah an einer Ecke',
  'Blocking access to a utility box':    'Versorgungskasten blockiert',
  'Not aligned with bike rack':          'Nicht am Ständer ausgerichtet',
  'Blocking a driveway':                 'Hofeinfahrt blockiert',
  'Parked in a narrow spot':             'Auf engem Platz',
  'Parked on road':                      'Auf der Fahrbahn',
  'Parked on free space':                'Auf freier Fläche',
  'Neatly aligned against surroundings': 'Ordentlich ausgerichtet',
  'Parked at bike rack':                 'Am Fahrradständer',
  'Parked in dedicated parking zone':    'In ausgewiesener Abstellzone',
  'Parked in a car parking space':       'Auf Kfz-Stellplatz',
  'Blocking a traffic island':           'Verkehrsinsel blockiert',
  'Blocking U-Bahn entrance':            'U-Bahn-Eingang blockiert',
  'Intrudes on sidewalk':                'Ragt auf den Gehweg',
  'Wild scooter pileup':                 'Rollerhaufen',
  'Parked on walkable space':            'Auf Gehfläche',
  'Not aligned with surroundings':       'Nicht ausgerichtet',
  'Parked among furniture':              'Zwischen Außenmobiliar abgestellt',
  'Blocking staircase':                  'Blockiert eine Treppe',
  'Not alligned with perpendicular bike rack': 'Nicht zum (Serien-)Fahrradständer ausgerichtet',
  'Niche Parking':                       'In einer Niche abgestellt',
  'Cobble Stone Strip inner side':       'Steht auf dem inneren Kopfsteinpflasterstreifen',
  'Cobble Stone Strip outer side':       'Steht auf dem äußeren Kopfsteinpflasterstreifen',
}